# Generated by Django 5.2.4 on 2025-08-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0002_tbapi_language_alter_tbapi_api_key_alter_tbapi_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbapi',
            name='language',
            field=models.CharField(default='en', max_length=100),
        ),
    ]
