# Generated by Django 5.2.4 on 2025-08-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0003_alter_tbapi_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbuser',
            name='profile',
            field=models.FileField(default='', upload_to='profile_images/'),
            preserve_default=False,
        ),
    ]
