# Generated by Django 5.2.4 on 2025-08-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0004_tbuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbuser',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
