# Generated by Django 5.2.4 on 2025-08-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0005_tbuser_email_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbuser',
            name='gmail',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
