# Generated by Django 5.2.4 on 2025-08-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0006_alter_tbuser_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbapi',
            name='toxic',
            field=models.CharField(default='no', max_length=100),
        ),
    ]
