# Generated by Django 5.2.4 on 2025-09-02 12:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0007_tbapi_toxic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gmail', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('questions', models.TextField()),
                ('feedback', models.TextField(blank=True)),
                ('status', models.CharField(default='no', max_length=100)),
            ],
        ),
    ]
